services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
